# Specify Python version and required system packages
[phases.setup]
nixPkgs = ["python311", "gcc"]

# Ensure pip is available and install dependencies
[phases.install]
cmds = [
    "python -m ensurepip --upgrade",
    "python -m pip install --upgrade pip",
    "pip install -r requirements.txt"
]

# Set environment variables for Python
[variables]
PYTHONUNBUFFERED = "1"
PYTHON_VERSION = "3.11"

# Start command
[start]
cmd = "python -m app.main"